title: BioInfo Workshop
description: Short-read analysis of bacterial pathogens

url: "https://bajicv.github.io"
baseurl: "/test_tutorial"

remote_theme: just-the-docs/just-the-docs@v0.12.0
color_scheme: github_light

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

search_enabled: true
enable_copy_code_button: true

aux_links:
  "Workshop repository":
    - "https://github.com/bajicv/test_tutorial"

# Render all Markdown pages with the theme, but do not automatically
# put every practical exercise into the navigation menu.
defaults:
  - scope:
      path: ""
    values:
      layout: default
      nav_exclude: true

callouts:
  note:
    title: "ℹ️ Note"
    color: blue

  tip:
    title: "💡 Tip"
    color: green

  important:
    title: "❗ Important"
    color: purple

  warning:
    title: "⚠️ Warning"
    color: yellow

  caution:
    title: "🛑 Caution"
    color: red

  question:
    title: "❓ Question"
    color: blue

  task:
    title: "✅ Task"
    color: green

  discussion:
    title: "💬 Discussion"
    color: purple

callouts_opacity: 0.3
